### ISSUE TITLE
Audio is very quiet

### ISSUE THREAD

**Issue by karai17** [notsecure/uTox#453]
While the audio quality is surprisingly clear, both myself and my chat partner were very quiet and we needed to turn our respective volumes up to unreasonable levels to be able to hear each other.

Google Hangouts seems to also have a problem with low volume, though Skype's volume is normalized pretty well.

**Comment by GrayHatter** [comment]
fixed, tag me otherwise

**Comment by Xunie** [comment]
@GrayHatter 
I just ran the latest version and it still isn't fixed.
I'm still getting obnoxiously low audio volume on my end.
I didn't see any commit that supposedly fixed this. Which commit would have fixed this problem?

**Comment by GrayHatter** [comment]
@irungentoo

**Comment by irungentoo** [comment]
@Xunie tell your friend to enable audio filtering in their client if you can't hear them.

**Comment by GrayHatter** [comment]
close as stale
