### ISSUE TITLE
libvpx

### ISSUE THREAD

**Issue by Sorunome** [notsecure/uTox#995]
I'm getting
[sorunome@sorunome-desktop utox-git]$ utox
utox: error while loading shared libraries: libvpx.so.1: cannot open shared object file: No such file or directory

I tried building tox-core and utox again, both via the archlinux repo thingy, same results.

[sorunome@sorunome-desktop utox-git]$ ls -l /usr/lib/libvpx*
lrwxrwxrwx 1 root root      15 Apr 18 12:41 /usr/lib/libvpx.so -> libvpx.so.2.0.0
lrwxrwxrwx 1 root root      15 Apr 18 12:41 /usr/lib/libvpx.so.2 -> libvpx.so.2.0.0
lrwxrwxrwx 1 root root      15 Apr 18 12:41 /usr/lib/libvpx.so.2.0 -> libvpx.so.2.0.0
-rwxr-xr-x 1 root root 2058736 Apr 18 12:41 /usr/lib/libvpx.so.2.0.0

I see that the file isn't there, but why isn't utox using the existing ones, especially after re-building?

**Comment by GrayHatter** [comment]
@zetok @haavardp

**Comment by haavardp** [comment]
Can you give us the output of `which utox`? Thanks.

**Comment by Sorunome** [comment]
[sorunome@sorunome-desktop ~]$ which utox
/usr/bin/utox


Also, i "fixed" it by creating a symlink to libvpx.so which is, i guess, more  hack than something else

**Comment by zetok** [comment]
dunno about "hack", since on Gentoo it's: ``/usr/lib64/libvpx.so.1 -> libvpx.so.1.3.0``

**Comment by irungentoo** [comment]
rebuilding uTox should fix this. You most likely updated libvpx without rebuilding uTox after.

**Comment by Sorunome** [comment]
I did try to re-build toxcore and utox after and it didn't fix it.

**Comment by irungentoo** [comment]
rebuilding toxcore?

**Comment by Sorunome** [comment]
since I wasn't 100% sure if the issue was toxcore or utox i just re-built both to realize that there was still the same problem ;)

**Comment by zetok** [comment]
After update from ``libvpx-1.3.0`` to ``1.4.0``:
![muh vpx2](https://cloud.githubusercontent.com/assets/3148759/7389642/ce97f6a2-ee67-11e4-94a7-0b9a5b22d3a0.png)

From ``libvpx`` changelog:
```
 v1.4.0

2015-04-03 v1.4.0 "Indian Runner Duck"
  This release includes significant improvements to the VP9 codec.

  - Upgrading:
    This release is ABI incompatible with 1.3.0. It drops the compatibility
    layer, requiring VPX_IMG_FMT_* instead of IMG_FMT_*, and adds several codec
    controls for VP9.
```

So.
Upstream doesn't provide symlinks, since ABI compatibility for (if I understood correctly) VP9 has been broken.

Welp. Good job ``libvpx`` …

Eh. Dunno what to do with this upstream problem, it also may cause problems for Gentoo overlay, I gotta test it with ``libvpx-1.4.0`` …

**Comment by zetok** [comment]
actually, after rebuilding toxcore and µTox on arch vm, it just works…

@Sorunome it looks to me like there's some problem with your system.

**Comment by Sorunome** [comment]
Did you try on arch?

**Comment by tsudoko** [comment]
@Sorunome
> actually, after rebuilding toxcore and µTox on arch vm, it just works…

**Comment by GrayHatter** [comment]
@Sorunome did you get it working, or are there still libvpx issues in the newest version of µTox and vpx tag me or reopen this

thanks!
